on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

name: resolvers
jobs:
  resolvers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Runing
        run: |
          wget https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json
          cat public-resolvers.json | grep -B 18 -A 2 '"proto": "DNSCrypt"' | grep -B 6 -A 14 '"dnssec": true,' | grep -B 14 -A 6 '"nolog": true,' | grep -B 7 -A 13 '"ipv6": false,' | grep '"name":' | grep -v 'family' | grep -v 'cleanbrowsing' | grep -v 'adguard' | grep -v 'sfw' | grep -v 'nogoogle' >>NoFilter.json
          cat public-resolvers.json | grep -B 18 -A 2 '"proto": "DNSCrypt"' | grep -B 6 -A 14 '"dnssec": true,' | grep -B 13 -A 7 '"nofilter": false,' | grep -B 14 -A 6 '"nolog": true,' | grep -B 7 -A 13 '"ipv6": false,' | grep '"name":' | grep -v 'family' | grep -v 'cleanbrowsing' | grep -v 'adguard' | grep -v 'sfw' | grep -v 'nogoogle' >>Filter.json
          rm -rf public-resolvers.json
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
